require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/client_sessions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ClientSession. As you add validations to ClientSession, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ClientSession.create! valid_attributes
      get client_sessions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      client_session = ClientSession.create! valid_attributes
      get client_session_url(client_session)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_client_session_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      client_session = ClientSession.create! valid_attributes
      get edit_client_session_url(client_session)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ClientSession" do
        expect {
          post client_sessions_url, params: { client_session: valid_attributes }
        }.to change(ClientSession, :count).by(1)
      end

      it "redirects to the created client_session" do
        post client_sessions_url, params: { client_session: valid_attributes }
        expect(response).to redirect_to(client_session_url(ClientSession.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ClientSession" do
        expect {
          post client_sessions_url, params: { client_session: invalid_attributes }
        }.to change(ClientSession, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post client_sessions_url, params: { client_session: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested client_session" do
        client_session = ClientSession.create! valid_attributes
        patch client_session_url(client_session), params: { client_session: new_attributes }
        client_session.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the client_session" do
        client_session = ClientSession.create! valid_attributes
        patch client_session_url(client_session), params: { client_session: new_attributes }
        client_session.reload
        expect(response).to redirect_to(client_session_url(client_session))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        client_session = ClientSession.create! valid_attributes
        patch client_session_url(client_session), params: { client_session: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested client_session" do
      client_session = ClientSession.create! valid_attributes
      expect {
        delete client_session_url(client_session)
      }.to change(ClientSession, :count).by(-1)
    end

    it "redirects to the client_sessions list" do
      client_session = ClientSession.create! valid_attributes
      delete client_session_url(client_session)
      expect(response).to redirect_to(client_sessions_url)
    end
  end
end
